#!/bin/bash

set -x
#the initial DNS to look after is indicated in $1
DNS=$1
#the target is $2
TARGET=$2
#the dig command an doptions
DIG="dig +norecurse"

#how many iterations
HOPS=0

while(true)
do
	#hop+=1
	HOPS=$(($HOPS+1))
	echo try ${HOPS}: USING DNS $DNS

	#get the number of answer in the header field
	ANSWER=$($DIG @$DNS $TARGET | grep ';; flags' | awk -F ',' '{print $2;}' | awk '{print $2;}')

	if [ "$ANSWER" -eq 0 ]
	then
		#if the number is zero, use first server in the authority section to do the next query
		echo No answer returned, using first server in the AUTHORITY SECTION
		DNS=$($DIG @$DNS $TARGET | sed -n '/;; AUTHORITY SECTION:/{n;p}' | awk '{print $5;}')
	else
		#if the number of answer is not zero, print all the information in the answer section and exit
		$DIG @$DNS $TARGET | sed -n "/ANSWER SECTION:/, +${ANSWER}p"
		exit 0
	fi
done

